name: effectiveness
favicon: null
layout_spectrum: 0.08338101906701922
typography_spectrum: 0.5735515807755291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.45421455963514745
  lightness: 0.909540685126558
  saturation: 0.9800173479598016
  rhythmicContrast: 0.9943441015202552
purpose: []
