name: effectiveness
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12435
title: organisational effectiveness inspiration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7450a0'
    - '#afd4f0'
    - '#e6c0da'
    - '#9d84bc'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
